# Generated by Django 5.2.6 on 2026-02-13 21:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cle_utilisateur', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Clé unique d'identification interne de l'utilisateur.", unique=True)),
                ('type_compte', models.CharField(choices=[('CLIENT', 'Client'), ('ADMIN', 'Admin'), ('VALIDATEUR', 'Validateur')], default='CLIENT', help_text='Type de compte utilisateur (Client, Admin ou Validateur).', max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de création du compte utilisateur.')),
                ('derniere_connexion', models.DateTimeField(blank=True, help_text="Dernière connexion réussie de l'utilisateur.", null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', help_text='Statut actuel du compte (actif, inactif ou suspendu).', max_length=20)),
                ('tentatives_connexion', models.IntegerField(default=0, help_text='Nombre de tentatives de connexion récentes (anti-brute-force).')),
                ('token_reset_mdp', models.CharField(blank=True, help_text='Token temporaire pour la réinitialisation du mot de passe.', max_length=255, null=True)),
                ('date_token_reset', models.DateTimeField(blank=True, help_text='Date de génération du token de réinitialisation.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
                'ordering': ['-date_creation'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.CharField(blank=True, help_text='Adresse IP de la tentative de connexion.', max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, help_text="Informations sur le navigateur ou l'appareil utilisé.", null=True)),
                ('statut_connexion', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('BLOQUE', 'Bloqué')], help_text='Résultat de la tentative (succès, échec, bloqué).', max_length=20)),
                ('type_action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('TENTATIVE', 'Tentative')], help_text="Type d'action enregistrée (connexion, déconnexion, tentative).", max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'db_table': 'historique_connexion',
                'ordering': ['-date_connexion'],
            },
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='utilisateur_email_5ac882_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['type_compte', 'statut'], name='utilisateur_type_co_794f82_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['date_creation'], name='utilisateur_date_cr_cd896e_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueconnexion',
            index=models.Index(fields=['utilisateur', 'date_connexion'], name='historique__utilisa_5fdfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueconnexion',
            index=models.Index(fields=['statut_connexion'], name='historique__statut__74cea4_idx'),
        ),
    ]
