# Generated by Django 5.2.6 on 2026-03-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveIndex(
            model_name='utilisateur',
            name='utilisateur_email_5ac882_idx',
        ),
        migrations.RemoveIndex(
            model_name='utilisateur',
            name='utilisateur_type_co_794f82_idx',
        ),
        migrations.RemoveIndex(
            model_name='utilisateur',
            name='utilisateur_date_cr_cd896e_idx',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='cle_utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_token_reset',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='derniere_connexion',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='token_reset_mdp',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='type_compte',
        ),
        migrations.AddField(
            model_name='historiqueconnexion',
            name='identifiant_saisi',
            field=models.CharField(blank=True, help_text="Identifiant saisi lors d'une tentative (username/email).", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_connexion_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='est_bloque',
            field=models.BooleanField(default=False, help_text='Indique si le compte est bloqué.'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='est_verifie',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a vérifié son email."),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='users/profils/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('ORGANISATEUR', 'Organisateur'), ('UTILISATEUR', 'Utilisateur')], default='UTILISATEUR', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueconnexion',
            name='statut_connexion',
            field=models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('BLOQUE', 'Bloqué')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueconnexion',
            name='type_action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('TENTATIVE', 'Tentative')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueconnexion',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_connexions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='tentatives_connexion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table='utilisateurs',
        ),
    ]
