# Generated by Django 5.2.6 on 2026-02-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_offre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nb_personnes', models.PositiveIntegerField(default=1)),
                ('type_offre', models.CharField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('FAMILIALE', 'Familiale')], max_length=20)),
                ('stock_total', models.PositiveIntegerField()),
                ('stock_disponible', models.PositiveIntegerField()),
                ('date_debut_vente', models.DateTimeField()),
                ('date_fin_vente', models.DateTimeField()),
                ('lieu_evenement', models.CharField(blank=True, max_length=200, null=True)),
                ('discipline_sportive', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EPUISEE', 'Epuisée'), ('EXPIREE', 'Expirée')], default='ACTIVE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offre',
            },
        ),
    ]
