# Generated by Django 5.2.6 on 2026-02-13 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evenements', '0001_initial'),
        ('offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offre',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='evenements.evenement'),
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['evenement', 'statut'], name='offre_eveneme_6dd5fe_idx'),
        ),
    ]
