# Generated by Django 5.2.6 on 2026-04-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0002_initial'),
        ('offres', '000Y_migrate_typeoffre_to_categorie'),
    ]

    operations = [
    ]
