# Generated by Django 5.2.6 on 2026-04-21 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0003_alter_evenement_options_and_more'),
        ('offres', '0003_merge_20260421_1515'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='discipline_sportive',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='lieu_evenement',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='nb_personnes',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='type_offre',
        ),
        migrations.AlterField(
            model_name='offre',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='offres.categorieoffre'),
        ),
        migrations.AddIndex(
            model_name='categorieoffre',
            index=models.Index(fields=['active'], name='categorie_o_active_99f666_idx'),
        ),
        migrations.AddIndex(
            model_name='categorieoffre',
            index=models.Index(fields=['ordre_affichage'], name='categorie_o_ordre_a_9fed26_idx'),
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['categorie', 'statut'], name='offre_categor_f02e43_idx'),
        ),
        migrations.AddConstraint(
            model_name='offre',
            constraint=models.UniqueConstraint(fields=('evenement', 'categorie'), name='uniq_evenement_categorie'),
        ),
    ]
