# Generated by Django 5.2.6 on 2026-04-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0004_remove_offre_discipline_sportive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
