# Generated by Django 5.2.6 on 2026-04-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0005_alter_offre_prix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offre',
            options={'ordering': ['date_creation']},
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EPUISEE', 'Épuisée'), ('EXPIREE', 'Expirée')], default='ACTIVE', max_length=20),
        ),
    ]
