# Generated by Django 5.2.6 on 2026-05-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0006_alter_offre_options_alter_offre_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='stock_disponible',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='stock_total',
        ),
        migrations.AddField(
            model_name='categorieoffre',
            name='auto_apply_all_events',
            field=models.BooleanField(default=True, help_text='Si True, cette catégorie est appliquée automatiquement à tous les événements (SOLO/DUO/FAMILLE). Si False, elle est créée seulement pour des événements spécifiques.'),
        ),
        migrations.AddField(
            model_name='offre',
            name='quota_billets_restant',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de billets restants vendables pour cette catégorie sur cet événement.'),
        ),
        migrations.AddField(
            model_name='offre',
            name='quota_billets_total',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de billets vendables pour cette catégorie sur cet événement.'),
        ),
        migrations.AddIndex(
            model_name='categorieoffre',
            index=models.Index(fields=['auto_apply_all_events'], name='categorie_o_auto_ap_9baca5_idx'),
        ),
    ]
