# Generated by Django 5.2.6 on 2025-10-01 13:04

import django.db.models.deletion
import paiements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paniers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(default=paiements.models.generate_numero_commande, max_length=50, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_paiement', models.CharField(choices=[('ATTENTE', 'Attente'), ('PAYE', 'Payé'), ('ECHOUE', 'Echoué'), ('REMBOURSE', 'Remboursé')], default='ATTENTE', max_length=20)),
                ('methode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('panier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='paniers.panier')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commande',
                'indexes': [models.Index(fields=['utilisateur', 'date_commande'], name='commande_utilisa_3697a6_idx')],
            },
        ),
    ]
