# Generated by Django 5.2.6 on 2026-02-13 21:55

import paiements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(default=paiements.models.generate_numero_commande, max_length=50, unique=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Identifiant de transaction externe (ex: Stripe, PayPal, etc.)', max_length=100, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_paiement', models.CharField(choices=[('ATTENTE', 'Attente'), ('PAYE', 'Payé'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], default='ATTENTE', max_length=20)),
                ('methode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commande',
                'ordering': ['-date_commande'],
            },
        ),
    ]
