# Generated by Django 5.2.6 on 2026-03-14 03:18

import django.db.models.deletion
import paiements.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('statut', models.CharField(choices=[('INITIE', 'Initié'), ('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé')], db_index=True, default='INITIE', max_length=20)),
                ('provider', models.CharField(choices=[('MOCK', 'Mock'), ('STRIPE', 'Stripe'), ('PAYPAL', 'Paypal')], db_index=True, default='MOCK', max_length=20)),
                ('reference', models.CharField(db_index=True, default=paiements.models.generate_reference, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.commande')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paiement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
