# Generated by Django 5.2.6 on 2025-10-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(choices=[('ATTENTE', 'Attente'), ('PAYE', 'Payé'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], default='ATTENTE', max_length=20),
        ),
    ]
