# Generated by Django 5.2.6 on 2026-02-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiements', '0001_initial'),
        ('paniers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='paniers.panier'),
        ),
    ]
