# Generated by Django 5.2.6 on 2025-10-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_alter_commande_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={},
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(choices=[('ATTENTE', 'Attente'), ('PAYE', 'Payé'), ('ECHOUE', 'Echoué'), ('REMBOURSE', 'Remboursé')], default='ATTENTE', max_length=20),
        ),
    ]
