# Generated by Django 5.2.6 on 2025-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_alter_commande_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Identifiant de transaction externe (ex: Stripe, PayPal, etc.)', max_length=100, null=True),
        ),
    ]
