# Generated by Django 5.2.6 on 2025-10-02 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiquesVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ventes', models.IntegerField(default=0)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('moyenne_ventes_jour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pic_ventes_heure', models.DateTimeField(blank=True, null=True)),
                ('offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='offres.offre')),
            ],
            options={
                'db_table': 'statistiques_vente',
            },
        ),
    ]
