# Generated by Django 5.2.6 on 2026-02-13 21:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiquesVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ventes', models.IntegerField(default=0)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('moyenne_ventes_jour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pic_ventes_heure', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Statistique de Vente',
                'verbose_name_plural': 'Statistiques de Ventes',
                'db_table': 'statistiques_vente',
                'ordering': ['-date_derniere_maj'],
            },
        ),
    ]
