# Generated by Django 5.2.6 on 2026-02-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiquesvente',
            name='offre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='offres.offre'),
        ),
        migrations.AddIndex(
            model_name='statistiquesvente',
            index=models.Index(fields=['offre'], name='statistique_offre_i_9f40b6_idx'),
        ),
        migrations.AddIndex(
            model_name='statistiquesvente',
            index=models.Index(fields=['-date_derniere_maj'], name='statistique_date_de_3e7c9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='statistiquesvente',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_ventes__gte', 0)), name='stats_nombre_ventes_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='statistiquesvente',
            constraint=models.CheckConstraint(condition=models.Q(('chiffre_affaires__gte', 0)), name='stats_chiffre_affaires_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='statistiquesvente',
            constraint=models.CheckConstraint(condition=models.Q(('moyenne_ventes_jour__gte', 0)), name='stats_moy_ventes_jour_non_negatif'),
        ),
    ]
