# Generated by Django 5.2.6 on 2025-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistiquesvente',
            options={'verbose_name': 'Statistique de Vente', 'verbose_name_plural': 'Statistiques de Ventes'},
        ),
        migrations.AddIndex(
            model_name='statistiquesvente',
            index=models.Index(fields=['offre'], name='statistique_offre_i_9f40b6_idx'),
        ),
        migrations.AddIndex(
            model_name='statistiquesvente',
            index=models.Index(fields=['-date_derniere_maj'], name='statistique_date_de_3e7c9d_idx'),
        ),
    ]
