# Generated by Django 5.2.6 on 2025-10-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_statistiquesvente_options_and_more'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistiquesvente',
            options={'ordering': ['-date_derniere_maj'], 'verbose_name': 'Statistique de Vente', 'verbose_name_plural': 'Statistiques de Ventes'},
        ),
        migrations.AddConstraint(
            model_name='statistiquesvente',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_ventes__gte', 0)), name='stats_nombre_ventes_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='statistiquesvente',
            constraint=models.CheckConstraint(condition=models.Q(('chiffre_affaires__gte', 0)), name='stats_chiffre_affaires_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='statistiquesvente',
            constraint=models.CheckConstraint(condition=models.Q(('moyenne_ventes_jour__gte', 0)), name='stats_moy_ventes_jour_non_negatif'),
        ),
    ]
