# Generated by Django 5.2.6 on 2026-04-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='discipline_sportive',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='lieu_evenement',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='nom',
        ),
        migrations.AddField(
            model_name='evenement',
            name='description_courte',
            field=models.TextField(blank=True, help_text='Description affichée dans la boutique'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='description_longue',
            field=models.TextField(blank=True, help_text='Description affichée sur la page détail'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='discipline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='evenement',
            name='heure_evenement',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(default='Paris', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evenement',
            name='nom_evenement',
            field=models.CharField(default='Foot 2', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evenement',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterModelTable(
            name='evenement',
            table=None,
        ),
    ]
