# Generated by Django 5.2.6 on 2026-04-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_remove_evenement_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'ordering': ['date_evenement'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_evenement',
            field=models.DateField(verbose_name="Date de l'événement"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description_courte',
            field=models.TextField(blank=True, help_text='Description affichée sur la carte de la boutique', verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description_longue',
            field=models.TextField(blank=True, help_text='Description affichée sur la page détail', verbose_name='Description longue'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='discipline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Discipline sportive'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='heure_evenement',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure de l'événement"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name="Image de l'événement"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(max_length=255, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='nom_evenement',
            field=models.CharField(max_length=255, verbose_name="Nom de l'événement"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
    ]
