# Generated by Django 5.2.6 on 2026-04-27 16:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0003_alter_evenement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='prix_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix de base (SOLO = x1). DUO/FAMILLE = multiplicateur nb_personnes.', max_digits=10),
        ),
    ]
