# Generated by Django 5.2.6 on 2026-04-29 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0004_evenement_prix_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de début de l'événement"),
            preserve_default=False,
        ),
    ]
