# Generated by Django 5.2.6 on 2026-04-29 21:00

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0005_evenement_date_debut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'ordering': ['date_debut'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='date_evenement',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='heure_evenement',
        ),
        migrations.AddField(
            model_name='evenement',
            name='date_fin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date et heure de fin de l'événement"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_debut',
            field=models.DateTimeField(verbose_name="Date et heure de début de l'événement"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description_courte',
            field=models.TextField(blank=True, help_text='Affichée sur la carte boutique', verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description_longue',
            field=models.TextField(blank=True, help_text='Affichée sur la page détail', verbose_name='Description longue'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='prix_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix de base SOLO. DUO/FAMILLE = multiplicateur.', max_digits=10, verbose_name='Prix de base'),
        ),
    ]
