# Generated by Django 5.2.6 on 2026-02-13 21:55

import billets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EBillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_billet', models.CharField(default=billets.models.generate_numero_billet, help_text='Numéro public unique du billet.', max_length=50, unique=True)),
                ('date_achat', models.DateTimeField(auto_now_add=True, help_text="Date et heure d'achat du billet.")),
                ('cle_achat', models.CharField(default=billets.models.generate_cle_achat, help_text="Identifiant interne d'achat (UUID).", max_length=64)),
                ('cle_finale', models.CharField(db_index=True, default=billets.models.generate_uuid, editable=False, help_text='Clé finale utilisée pour le QR code et la validation.', max_length=64, unique=True)),
                ('qr_code', models.TextField(blank=True, help_text='Image du QR code encodée en base64.')),
                ('prix_paye', models.DecimalField(decimal_places=2, help_text='Prix payé pour ce billet.', max_digits=8)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('UTILISE', 'Utilisé'), ('ANNULE', 'Annulé'), ('EXPIRE', 'Expiré')], db_index=True, default='VALIDE', help_text='Statut actuel du billet.', max_length=20)),
                ('date_utilisation', models.DateTimeField(blank=True, db_index=True, help_text='Date et heure de validation/utilisation du billet.', null=True)),
                ('lieu_utilisation', models.CharField(blank=True, help_text='Lieu où le billet a été validé (ex: Entrée A).', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'E-Billet',
                'verbose_name_plural': 'E-Billets',
                'db_table': 'e_billet',
                'ordering': ['-date_achat'],
            },
        ),
    ]
