# Generated by Django 5.2.6 on 2025-10-01 13:04

import billets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EBillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_billet', models.CharField(default=billets.models.generate_numero_billet, max_length=50, unique=True)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('cle_achat', models.CharField(default=billets.models.generate_cle_achat, max_length=255)),
                ('cle_finale', models.CharField(default=billets.models.generate_uuid, editable=False, max_length=512)),
                ('qr_code', models.TextField(blank=True)),
                ('prix_paye', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('UTILISE', 'Utilisé'), ('ANNULE', 'Annulé'), ('EXPIRE', 'Expiré')], default='VALIDE', max_length=20)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('lieu_utilisation', models.CharField(blank=True, max_length=200, null=True)),
                ('id_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billets_valides', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebillets', to='offres.offre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebillets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'e_billet',
                'indexes': [models.Index(fields=['numero_billet'], name='e_billet_numero__e602e4_idx')],
            },
        ),
    ]
