# Generated by Django 5.2.6 on 2026-03-20 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billets', '0001_initial'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebillet',
            name='offre',
            field=models.ForeignKey(help_text='Offre ou pack lié à ce billet.', on_delete=django.db.models.deletion.CASCADE, related_name='ebillets', to='offres.offre'),
        ),
    ]
