# Generated by Django 5.2.6 on 2025-10-02 21:20

import billets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebillet',
            old_name='id_validateur',
            new_name='validateur',
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='cle_finale',
            field=models.CharField(default=billets.models.generate_uuid, editable=False, max_length=512, unique=True),
        ),
    ]
