# Generated by Django 5.2.6 on 2026-02-13 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ebillet',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur propriétaire du billet.', on_delete=django.db.models.deletion.CASCADE, related_name='ebillets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ebillet',
            name='validateur',
            field=models.ForeignKey(blank=True, help_text='Utilisateur (valideur) ayant scanné ou validé le billet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billets_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ebillet',
            index=models.Index(fields=['numero_billet'], name='e_billet_numero__e602e4_idx'),
        ),
        migrations.AddIndex(
            model_name='ebillet',
            index=models.Index(fields=['cle_finale'], name='e_billet_cle_fin_e9c754_idx'),
        ),
        migrations.AddIndex(
            model_name='ebillet',
            index=models.Index(fields=['statut'], name='e_billet_statut_9c3df1_idx'),
        ),
        migrations.AddIndex(
            model_name='ebillet',
            index=models.Index(fields=['date_utilisation'], name='e_billet_date_ut_869b66_idx'),
        ),
    ]
