# Generated by Django 5.2.6 on 2025-10-14 16:44

import billets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0002_rename_id_validateur_ebillet_validateur_and_more'),
        ('offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebillet',
            options={'ordering': ['-date_achat'], 'verbose_name': 'E-Billet', 'verbose_name_plural': 'E-Billets'},
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='cle_achat',
            field=models.CharField(default=billets.models.generate_cle_achat, help_text="Identifiant interne d'achat (UUID).", max_length=255),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='cle_finale',
            field=models.CharField(db_index=True, default=billets.models.generate_uuid, editable=False, help_text='Clé finale utilisée pour le QR code et la validation.', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='date_achat',
            field=models.DateTimeField(auto_now_add=True, help_text="Date et heure d'achat du billet."),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='date_utilisation',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date et heure de validation/utilisation du billet.', null=True),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='lieu_utilisation',
            field=models.CharField(blank=True, help_text='Lieu où le billet a été validé (ex: Entrée A).', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='numero_billet',
            field=models.CharField(default=billets.models.generate_numero_billet, help_text='Numéro public unique du billet.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='offre',
            field=models.ForeignKey(help_text='Offre ou pack lié à ce billet.', on_delete=django.db.models.deletion.CASCADE, related_name='ebillets', to='offres.offre'),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='prix_paye',
            field=models.DecimalField(decimal_places=2, help_text='Prix payé pour ce billet.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='qr_code',
            field=models.TextField(blank=True, help_text='Image du QR code encodée en base64.'),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='statut',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('UTILISE', 'Utilisé'), ('ANNULE', 'Annulé'), ('EXPIRE', 'Expiré')], db_index=True, default='VALIDE', help_text='Statut actuel du billet.', max_length=20),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur propriétaire du billet.', on_delete=django.db.models.deletion.CASCADE, related_name='ebillets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='validateur',
            field=models.ForeignKey(blank=True, help_text='Utilisateur (valideur) ayant scanné ou validé le billet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billets_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ebillet',
            index=models.Index(fields=['cle_finale'], name='e_billet_cle_fin_e9c754_idx'),
        ),
        migrations.AddIndex(
            model_name='ebillet',
            index=models.Index(fields=['statut'], name='e_billet_statut_9c3df1_idx'),
        ),
        migrations.AddIndex(
            model_name='ebillet',
            index=models.Index(fields=['date_utilisation'], name='e_billet_date_ut_869b66_idx'),
        ),
    ]
