# Generated by Django 5.2.6 on 2026-06-06 17:38

import billets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebillet',
            name='cle_achat',
            field=models.CharField(default=billets.models.generate_cle_achat, help_text="Identifiant interne d'achat.", max_length=64),
        ),
        migrations.AlterField(
            model_name='ebillet',
            name='cle_finale',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Clé finale dérivée (clé utilisateur + clé achat), utilisée pour le QR code et la validation.', max_length=64, unique=True),
        ),
    ]
