# Generated by Django 5.2.6 on 2026-03-20 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('RESERVATION', 'Réservation'), ('PAIEMENT', 'Paiement'), ('OFFRE', 'Offre'), ('SYSTEME', 'Système'), ('RAPPEL', 'Rappel')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='evenements.evenement')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
