# Generated by Django 5.2.6 on 2026-02-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='offres.offre'),
        ),
    ]
