# Generated by Django 5.2.6 on 2026-02-13 21:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('VALIDE', 'Valide'), ('ABANDONNE', 'Abandonné'), ('EXPIRE', 'Expiré')], default='ACTIF', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'panier',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sous_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres.offre')),
            ],
            options={
                'db_table': 'ligne_panier',
            },
        ),
    ]
