# Generated by Django 5.2.6 on 2026-03-20 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paniers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paniers.panier'),
        ),
        migrations.AddIndex(
            model_name='panier',
            index=models.Index(fields=['utilisateur', 'statut'], name='panier_utilisa_b584f0_idx'),
        ),
        migrations.AddIndex(
            model_name='lignepanier',
            index=models.Index(fields=['panier'], name='ligne_panie_panier__1ff8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='lignepanier',
            index=models.Index(fields=['offre'], name='ligne_panie_offre_i_f0785e_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignepanier',
            constraint=models.UniqueConstraint(fields=('panier', 'offre'), name='uniq_panier_offre'),
        ),
        migrations.AddConstraint(
            model_name='lignepanier',
            constraint=models.CheckConstraint(condition=models.Q(('offre__isnull', False)), name='ligne_panier_offre_nn'),
        ),
        migrations.AddConstraint(
            model_name='lignepanier',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='ligne_panier_quantite_gt_0'),
        ),
    ]
