# Generated by Django 5.2.6 on 2025-10-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
        ('paniers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignepanier',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='panier',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('VALIDE', 'Valide'), ('ABANDONNE', 'Abandonné'), ('EXPIRE', 'Expiré')], default='ACTIF', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='lignepanier',
            unique_together={('panier', 'offre')},
        ),
    ]
