# Generated by Django 5.2.6 on 2026-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paniers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
