# Generated by Django 5.2.6 on 2025-10-02 22:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paniers', '0002_alter_lignepanier_sous_total_alter_panier_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignepanier',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lignepanier',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
