# Generated by Django 5.2.6 on 2025-10-31 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
        ('paniers', '0003_alter_lignepanier_prix_unitaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lignepanier',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='lignepanier',
            index=models.Index(fields=['offre'], name='ligne_panie_offre_i_f0785e_idx'),
        ),
        migrations.AddIndex(
            model_name='panier',
            index=models.Index(fields=['utilisateur', 'statut'], name='panier_utilisa_b584f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignepanier',
            constraint=models.UniqueConstraint(fields=('panier', 'offre'), name='uniq_panier_offre'),
        ),
        migrations.AddConstraint(
            model_name='lignepanier',
            constraint=models.CheckConstraint(condition=models.Q(('offre__isnull', False)), name='ligne_panier_offre_nn'),
        ),
        migrations.AddConstraint(
            model_name='lignepanier',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='ligne_panier_quantite_gt_0'),
        ),
    ]
